version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5
    working_directory: ~/mach
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
